version: "3.8"

services:
  api:
    build: .
    container_name: ecommerce_api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      # Uncomment below if you want to test Atlas inside container
      # - MONGO_URI=mongodb+srv://username:password@cluster0.mongodb.net/ecommerce_api
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: ecommerce_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
